"""Update Favorite model as many-to-many

Revision ID: 952c70f85c42
Revises: a10157fb2553
Create Date: 2025-05-14 16:39:15.132791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '952c70f85c42'
down_revision: Union[str, None] = 'a10157fb2553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favorite', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('favorite', 'music_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('favorite', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('favorite', 'music_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('favorite', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
