"""Initial migration

Revision ID: f8d52af029f6
Revises: 
Create Date: 2025-05-10 13:22:48.801169

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'f8d52af029f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
